<?php 
	$startDir='';
	for($i=0; $i<20; $i++) {
		if(file_exists($startDir.'pageStart.php')) {
			require $startDir.'pageStart.php';
			break;
		}
		else {
			$startDir='../'.$startDir;
		}
	}
	block(
		'Narmen Curency',
		'info',
		quick_array([
			'There are three forms of Narmen currency Mother of Pearl Chips (Chips, C), Pearls (P), and Iridescent Pearls (Irids, I). Iridescent pearls are infused with ambient magic and glow and sparkle in iridescent patterns. Chips come in various sizes creating pseudo-currency types that are worth their corresponding fraction of a chip such as Half Chips (Halves, 0x0.8 C), Quarter Chips (Quarters, 0x0.4 C), Eighth Chips (Eighths, 0x0.2 C), Sixteenth Chips (Sehs (plural is the same as singular, pronounced like "says"), 0x0.1 C), and Double Sized Chips or Double Chips (Doubles, 0x2 C).',
			'One Pearl is worth 16 Chips and one Irid is worth 16 Pearls. When converting to the gold standard, one gold is worth one pearl though large prices can often be different between pearls and gold not because of conversion but because Narmen often hide price reductions from their advanced technology behind listing prices in gold at their usual price elsewhere and their discounted price in Irid. Since most individuals don\'t bother to do the conversion as 16:1 conversions are harder in base 10 societies, most people do not realize they are being cheated. The price reductions often aren\'t that large overall with successful general reduction of magic components reduced by 4% in magic items. Other reductions include not listing additional cost for high quality items such as "masterwork" items as it is assumed and changing the price of mundane items to only twice the necessary materials instead of three times. For the most part, only items over 8 irid (128 gp) are differentiated, simply listing the discounted actual price for both the gold piece and pearl/irid prices though shops that mostly serve outsiders will only list the regular non-discounted price of all of their items and other shops are likely to make you pay the higher price when using gold as a "foreign currency fee". It is very hard for non-Narmen to identify the scam they are only told the gold piece prices and the prices in irids, pearls, and chips will be written in the Narman language.',
			'Narmen see these behaviors as fair for two main reasons. Both stem from the tendency for Narmen to see themselves as superior to other races. So, the first is while they will agree to accept the currencies of "inferior" races, they increase the associated price for having to deal with them. The other is that many Narmen don\'t believe allowing the other races to benefit from their hard work as a race to increase the efficiency of construction. When confronted about the injustice, many will claim that they "helping" the economy of magic items elsewhere by not forcing other magic item creators to compete with their methods.',
			'',
			'The Narmen also have an additional type of item that is often treated as particularly large currency. The Imperial Narmen government collects diamond dust from the diamond mount and packages it into small bags of a specific amount. This bags vary in size and purity but are generally consistent across bags of the same cost of diamond and each contains exactly as much as they are labelled as. These bags are magic sealed against tampering and each possess a unique identifier that can be used to validate it is a genuine bag of diamond dust distributed by the government. These pouches are designed for use with ii/ aa/brilliant_material_stone|brilliant material stones/aa /ii and are priced matching their "equivalent component cost" (ecc) in irid and are sold by the government and passed as currency at half their ecc value meaning that each bag contains four times its market value in diamond dust. This is possible due in large part to the amount of diamond produced by the diamond mount and the level of anti-counterfeit and anti-tamper measures in place on the bags. In addition to the unique identifiers the bags are given, each bag is nearly indestructible and impenetrable and any successful damage to the bag or modification of its contents from outside sources will destroy the entire bag and all its contents in addition to anything already removed from the bag. If the entire contents of the bag are not expended when using it to cast a spell it will transmute the necessary amount of diamond dust into quartz while still allowing the original form of the dust to be used in the spell thus reducing the amount remaining in the bag. Such partially full bag will impart their current amount to anyone that touches it and are generally considered no longer valid for trading as currency though some people will still trade them.',
			'These diamond dust pouches generally come in 0x20, 0x40, 0x80, 0x100, 0x200, 0x400, 0x800, 0x1000, 0x2000, and 0x4000 ecc worth of diamond dust. This is 1,024, 2,048, 4,096, 8,192, 16,384, 32,768, 65,536, 131,072, 262,144, and 524,288 gp worth of diamond dust respectively. Simply touching a bag will impart its current and original value to the individual who touched it.',
			'It should be noted that Narman, being an entire race where the only survivors are the descendants of the noble class, have a very different sense of money and it is possible for a non-Narman to become very rich by robbing one.'
		])
	);
	require $startDir.'pageEnd.php';
?>