<?php 
	$startDir='';
	for($i=0; $i<20; $i++) {
		if(file_exists($startDir.'pageStart.php')) {
			require $startDir.'pageStart.php';
			break;
		}
		else {
			$startDir='../'.$startDir;
		}
	}
	block(
		'Cosmere',
		'setting',
		quick_array([
			'The Cosmere is the setting of multiple series and stand alone books by the author Brandon Sanderson. Each of these books and series take place on different planets and while the underlying principles of the universe remain constant, each planet has a diferent and unique system of magic. These systems are gnerally classified as being very hard magic systems where the exact limitations and cpabilities are set forth despite their open ended nature. Here I have created my interpretation of rules for several of the major systems of magic as well as some of the major reoccuring concepts.',
			'<h3>Overview</h3>',
			'/mm/ In the universe of the Cosmere, there are 16 shards of power called the bb/Shards of Adonalsium/bb. Long ago, Adonalsium was shattered into 16 parts to create these shards. Shards are usually held by an individual who is generally referred to as the same entity, with the individual being called the vessel while the rest is called the power. Power from these shards forms all processes and transformation in the physical realm. Beyond this, Shards can "invest" a planet infusing its environment with power and ingraining the power of the shard into a system of magic unique to that planet. This also includes a specific method via which investiture can be acquired on that world. If multiple Shards invest the same world, the magic will be powered by a mixture of them and/or they will create different facets of the magic powered by the different Shards. Despite each planet having different magic, each planet\'s magic is able to be brought and performed on any planet. The power that comes from these Shards is called bb/investiture/bb, and is used to power all magic native to the Cosmere. It is possible for an individual to hold a mere fragment of a shard\'s power but one large enough to make them at least briefly deific. Such individuals, even after they lose such power, are referred to as splinters.',
			'/mm/ Each Shard holds exactly one sixteenth of all investiture and this amount cannot be changed. Most of this investiture is held in the Spiritual Realm, but can enter the Physical Realm through numerous methods. The most direct way is around a Perpendicularity. bb/Perpendicularities/bb are able to be formed by large masses of investiture and each Shard has their own. These Perpendicularities can be visible as a vertical beam of light or completely hidden and leak investiture into their surroundings, though most have some method of capturing it as it exits to various effects, though most commonly collects in a pool on the ground at the base of the perpendicularity. Investiture takes multiple forms in different states of matter though some the details vary per Shard and world. In solid form, investiture forms what is called bb/god-metal/bb. Each god-metal corresponds to the investiture of a specific Shard or ratios of the power of different Shards. God-metals can be alloyed but these alloys do not match what is produced when the investiture is mixed before taking solid form. In solid form, investiture can be used as most other materials though it is incredibly durable and difficult to shape mechanically. Solid investiture is nearly immune to being further invested in most cases and exists across multiple realms allowing it to interact with otherwise non-solid objects in some cases. In liquid form, investiture generally takes the form of a brightly glowing liquid though it can be supernaturally dark instead and on some worlds may not glow at all. Liquid investiture grants the most direct access to the power and direct contact can have powerful effects up to becoming a splinter. In gaseous form, investiture takes the form of a brightly glowing white vapor that takes on one of various hues around its edges depending the Shards it comes from though some are dark like the liquid forms instead but will continue to have a different color on their edges. Investiture that is dark in liquid form will also be dark in gaseous form. On some planets gaseous investiture may take a different form such a thick fog.',
			'/mm/ Investiture can come in two variants of the normal. First, investiture can be corrupted by Shards or by specially prepared tools of a Shard. bb/Corrupted investiture/bb becomes red and allows the Shard who corrupted it to co-opt the power. Secondly, through special means, investiture can have its polarity flipped creating anti-investiture. bb/Anti-investiture/bb will be supernaturally dark when it would otherwise be glowing and vice versa. Anti-investiture reacts with investiture of that type effectively annihilating both while releasing large quantities of energy. When done in a contained space this can result in an explosion.',
			'/mm/ When using magic powered by investiture, the user must have bb/intent/bb to some degree dependent on the specific magic being used. The user must also be able to access the needed investiture to power the magic. While possible to use investiture from a different shard to power magic, it often requires preparation and modification and is usually quite difficult without the aid of a Shard.',
			'/mm/ In the Cosmere, there are three realms.',
			'/mm/ The bb/Physical Realm/bb is largely identical in composition to the material plane with numerous planets each orbiting stars themselves orbiting through numerous massive galaxies.',
			'/mm/ The bb/Cognitive Realm/bb is formed from the idea of objects as they exist in the Physical Realm. Every object and creature on a world can be found on its corresponding planet in the Cognitive Realm. While in the Cognitive Realm, creatures in Physical Realm are visible as flames hovering the air though the appearance of objects varies based on the world potentially appearing as though made of mist or as a sea of beads. Whatever form they take, physical objects make up an area which approximates a fluid sea to most creatures upon which they cannot float and will sink and drown if they are caught in it. These seemingly oceans shore up where the land changes to water in the Physical Realm, presumably due to creatures having less thoughts of objects hidden under the water, though ships will form moving ponds of a sort, filled with the objects that make up the ship and everything on it. By touching the representation of a creature or object in the Cognitive Realm, an individual can learn what an object is, or more specifically, what an object is thought to be and thinks of itself as. If done properly, creatures in the Cognitive Realm can cause the representation of an object in the Cognitive Realm to manifest the original object as it thinks itself is in the Cognitive Realm. This has no effect in the Physical Realm but does allow creatures to take advantage of an object they have encountered. The cognitive form of an object can be moved to a location other than its exact position in the Physical Realm but may resist being pulled away and may attempt to move itself back if left unattended. An inanimate object thinks of itself as a conglomeration of the thoughts people have most frequently about it. Such as a log that is part of a pile which has for a long time been part of a fire in a fireplace will think of itself as being a charred log that is on fire and providing heat and light. Because an object manifests as it thinks of itself, the form it manifests as may differ from its true form.',
			'/mm/ Little is known about the bb/Spiritual Realm/bb as there is no known way for mortals to access the Spiritual Realm. What is known is that it contains what is often referred to as spiritual DNA, soulwebs, or spiritwebs which is a spiritual representation of the essence of a creature including an idealized version of them as a part of their spiritual identity, and their invested abilities. The Spiritual Realm also contains cords that tie creatures and objects together as a representation of spiritual connection between people, objects, and abstract concepts. Any connection (friends, parents, siblings, enemies, subjects, intertwined destinies, contractual partners, colleagues, spouses, patrons, owners, a lock with the matching key, a person to their country, etc.) is stored in the Spiritual Realm. The Spiritual Realm also houses the concept of fortune and luck. The physical properties of the Spiritual Realm are largely unknown, though it is known that there is no concept of time or space and that by seeing through it, it is possible to view both past events and predictions of the future though these can be modified or hidden by various means.',
			'More information about the world as well as proper lore explanations can be found on the <a href="https://coppermind.net/wiki/Cosmere">Wiki</a>.'
		]),
		true
	);
	require $startDir.'pageEnd.php';
?>