<?php require '../../pageStart.php'; ?>
<title>Runed Chain</title>
<?php
	magicItemBlockAuto(
		"Runed Chain",
		"Necromancy",
		15,
		"none",
		"—",
		20,
		"Each link of this long +5 ii/Agile Ghost-Touch Frost Prehensile Slithering Vicious/ii Spiresteel Spiked-Chain has a glowing blue rune engraved onto it. Other than being oddly heavy, it appears to be made of same material as the spire and yet careful analysis will reveal that it must have formed in its current shape. The chain seems to move on its own when wielded by a creature though this property is unnoticed by its wielder. When not in use, the chain often becomes wrapped around the wielder's arm. When used it tears at the mind and soul of its target and invigorates its wielder. When used on a living or undead creature, the chain restores a number of hit points equal to half the damage dealt. Excess hit points after both the healing and the vicious property are applied above a creatures maximum are lost. 3 times per day, this chain can gain the reach property for 1 round.
When an enemy is hit with the Runed Chain, the wielder can choose to attempt a grapple as a free action, without provoking an attack of opportunity, using the the chain's caster level plus it's enhancement bonus in place of the wielder's CMB. (normally a +20) While a target is grappled in this way the chain cannot be used but the wielder does not gain the grappled condition. Each time the chain is used to successfully maintain the grapple, the target is damaged by the chain as though by a successful attack, healing and damaging the wielder as appropriate. In addition, on a successful check to maintain the grapple, the target can be moved, pinned, or tied up as per the grapple combat maneuver using the chain. Any action taken while a creature is pinned or tied up with the chain forces the creature to take 2d4 piercing damage and 1d6 cold damage. If the chain is released while a creature is grappled or if the wielder chooses to release the target the chain falls off and the creature is released. If the chain is released while the creature is pinned the chain remains wrapped around the creature and maintains the grapple for an additional 1d4 rounds but the creature does not take the cold damage when taking an action. If the chain is released while a creature is tied up with it, the creature continues to be tied up as per the grapple condition but taking a action no longer forces the creature to take the cold damage.
If a creature is killed by the Runed Chain, the creature's soul is consumed by the chain and adds another link with a rune, chosen to best represent their deeds and experiences. Similarly, if a creature is killed while wielding the chain, their soul is consumed adding a link with an appropriate rune. In either case, the link must be destroyed before the creature can be resurrected. Once a link is destroyed, the soul contained in therein is freed and sent on its normal path to the afterlife. Each link has 30 hardness and 115 hit points. Destroying a link releases an explosion of energy dealing 5d6 damage to creatures within 30 feet. This damage is half cold and half negative energy. To undead, this damage is instead entirely as the divine power from ii/flame strike/ii. If a link is broken, the links on either side pull together and reform the chain. Speak with dead can be used to speak with the souls in the various links regardless of whether anything is left of their form, though most souls that have been in the chain for more than a few days largely only wail and moan when spoken to. Despite their nature, the links do not register for abilities that detect souls, living, dead, or undead and instead appear as inanimate objects.",
		true,
		"All of the Runed Chain's links must be destroyed. When found, it has 4d6 times 10 plus 1d10 links."
	);
	require '../../pageEnd.php';
?>